package com.cricketleagueanalyser.enums;

public enum SortByField {
    AVG, STRIKINGRATES, SIXFOURS, SIXFOURSAVG, AVGWITHSTRIKERATE, MAXRUNSWITHBESTAVERAGE, ECONOMY, FOURFIVEWICKETWITHSTRIKERATES, WICKETWITHAVERAGE;
}
